// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/clevertechware/gerer-les-transactions-en-base-de-donnees/internal/domain"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// CompanyService is an autogenerated mock type for the companyService type
type CompanyService struct {
	mock.Mock
}

type CompanyService_Expecter struct {
	mock *mock.Mock
}

func (_m *CompanyService) EXPECT() *CompanyService_Expecter {
	return &CompanyService_Expecter{mock: &_m.Mock}
}

// CreateCompany provides a mock function with given fields: ctx, company
func (_m *CompanyService) CreateCompany(ctx context.Context, company *domain.Company) error {
	ret := _m.Called(ctx, company)

	if len(ret) == 0 {
		panic("no return value specified for CreateCompany")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Company) error); ok {
		r0 = rf(ctx, company)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CompanyService_CreateCompany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCompany'
type CompanyService_CreateCompany_Call struct {
	*mock.Call
}

// CreateCompany is a helper method to define mock.On call
//   - ctx context.Context
//   - company *domain.Company
func (_e *CompanyService_Expecter) CreateCompany(ctx interface{}, company interface{}) *CompanyService_CreateCompany_Call {
	return &CompanyService_CreateCompany_Call{Call: _e.mock.On("CreateCompany", ctx, company)}
}

func (_c *CompanyService_CreateCompany_Call) Run(run func(ctx context.Context, company *domain.Company)) *CompanyService_CreateCompany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Company))
	})
	return _c
}

func (_c *CompanyService_CreateCompany_Call) Return(_a0 error) *CompanyService_CreateCompany_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CompanyService_CreateCompany_Call) RunAndReturn(run func(context.Context, *domain.Company) error) *CompanyService_CreateCompany_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCompany provides a mock function with given fields: ctx, id
func (_m *CompanyService) DeleteCompany(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCompany")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CompanyService_DeleteCompany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCompany'
type CompanyService_DeleteCompany_Call struct {
	*mock.Call
}

// DeleteCompany is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *CompanyService_Expecter) DeleteCompany(ctx interface{}, id interface{}) *CompanyService_DeleteCompany_Call {
	return &CompanyService_DeleteCompany_Call{Call: _e.mock.On("DeleteCompany", ctx, id)}
}

func (_c *CompanyService_DeleteCompany_Call) Run(run func(ctx context.Context, id uuid.UUID)) *CompanyService_DeleteCompany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *CompanyService_DeleteCompany_Call) Return(_a0 error) *CompanyService_DeleteCompany_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CompanyService_DeleteCompany_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *CompanyService_DeleteCompany_Call {
	_c.Call.Return(run)
	return _c
}

// GetCompany provides a mock function with given fields: ctx, id
func (_m *CompanyService) GetCompany(ctx context.Context, id uuid.UUID) (*domain.Company, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetCompany")
	}

	var r0 *domain.Company
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Company, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Company); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Company)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CompanyService_GetCompany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCompany'
type CompanyService_GetCompany_Call struct {
	*mock.Call
}

// GetCompany is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *CompanyService_Expecter) GetCompany(ctx interface{}, id interface{}) *CompanyService_GetCompany_Call {
	return &CompanyService_GetCompany_Call{Call: _e.mock.On("GetCompany", ctx, id)}
}

func (_c *CompanyService_GetCompany_Call) Run(run func(ctx context.Context, id uuid.UUID)) *CompanyService_GetCompany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *CompanyService_GetCompany_Call) Return(_a0 *domain.Company, _a1 error) *CompanyService_GetCompany_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CompanyService_GetCompany_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.Company, error)) *CompanyService_GetCompany_Call {
	_c.Call.Return(run)
	return _c
}

// ListCompanies provides a mock function with given fields: ctx
func (_m *CompanyService) ListCompanies(ctx context.Context) ([]domain.Company, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListCompanies")
	}

	var r0 []domain.Company
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Company, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Company); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Company)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CompanyService_ListCompanies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCompanies'
type CompanyService_ListCompanies_Call struct {
	*mock.Call
}

// ListCompanies is a helper method to define mock.On call
//   - ctx context.Context
func (_e *CompanyService_Expecter) ListCompanies(ctx interface{}) *CompanyService_ListCompanies_Call {
	return &CompanyService_ListCompanies_Call{Call: _e.mock.On("ListCompanies", ctx)}
}

func (_c *CompanyService_ListCompanies_Call) Run(run func(ctx context.Context)) *CompanyService_ListCompanies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *CompanyService_ListCompanies_Call) Return(_a0 []domain.Company, _a1 error) *CompanyService_ListCompanies_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CompanyService_ListCompanies_Call) RunAndReturn(run func(context.Context) ([]domain.Company, error)) *CompanyService_ListCompanies_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCompany provides a mock function with given fields: ctx, company
func (_m *CompanyService) UpdateCompany(ctx context.Context, company *domain.Company) error {
	ret := _m.Called(ctx, company)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCompany")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Company) error); ok {
		r0 = rf(ctx, company)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CompanyService_UpdateCompany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCompany'
type CompanyService_UpdateCompany_Call struct {
	*mock.Call
}

// UpdateCompany is a helper method to define mock.On call
//   - ctx context.Context
//   - company *domain.Company
func (_e *CompanyService_Expecter) UpdateCompany(ctx interface{}, company interface{}) *CompanyService_UpdateCompany_Call {
	return &CompanyService_UpdateCompany_Call{Call: _e.mock.On("UpdateCompany", ctx, company)}
}

func (_c *CompanyService_UpdateCompany_Call) Run(run func(ctx context.Context, company *domain.Company)) *CompanyService_UpdateCompany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Company))
	})
	return _c
}

func (_c *CompanyService_UpdateCompany_Call) Return(_a0 error) *CompanyService_UpdateCompany_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CompanyService_UpdateCompany_Call) RunAndReturn(run func(context.Context, *domain.Company) error) *CompanyService_UpdateCompany_Call {
	_c.Call.Return(run)
	return _c
}

// NewCompanyService creates a new instance of CompanyService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCompanyService(t interface {
	mock.TestingT
	Cleanup(func())
}) *CompanyService {
	mock := &CompanyService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
