// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/clevertechware/gerer-les-transactions-en-base-de-donnees/internal/domain"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MembershipService is an autogenerated mock type for the membershipService type
type MembershipService struct {
	mock.Mock
}

type MembershipService_Expecter struct {
	mock *mock.Mock
}

func (_m *MembershipService) EXPECT() *MembershipService_Expecter {
	return &MembershipService_Expecter{mock: &_m.Mock}
}

// AddMember provides a mock function with given fields: ctx, companyID, userID, role
func (_m *MembershipService) AddMember(ctx context.Context, companyID uuid.UUID, userID uuid.UUID, role string) (*domain.Membership, error) {
	ret := _m.Called(ctx, companyID, userID, role)

	if len(ret) == 0 {
		panic("no return value specified for AddMember")
	}

	var r0 *domain.Membership
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) (*domain.Membership, error)); ok {
		return rf(ctx, companyID, userID, role)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) *domain.Membership); ok {
		r0 = rf(ctx, companyID, userID, role)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Membership)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, string) error); ok {
		r1 = rf(ctx, companyID, userID, role)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MembershipService_AddMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddMember'
type MembershipService_AddMember_Call struct {
	*mock.Call
}

// AddMember is a helper method to define mock.On call
//   - ctx context.Context
//   - companyID uuid.UUID
//   - userID uuid.UUID
//   - role string
func (_e *MembershipService_Expecter) AddMember(ctx interface{}, companyID interface{}, userID interface{}, role interface{}) *MembershipService_AddMember_Call {
	return &MembershipService_AddMember_Call{Call: _e.mock.On("AddMember", ctx, companyID, userID, role)}
}

func (_c *MembershipService_AddMember_Call) Run(run func(ctx context.Context, companyID uuid.UUID, userID uuid.UUID, role string)) *MembershipService_AddMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(string))
	})
	return _c
}

func (_c *MembershipService_AddMember_Call) Return(_a0 *domain.Membership, _a1 error) *MembershipService_AddMember_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MembershipService_AddMember_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, string) (*domain.Membership, error)) *MembershipService_AddMember_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveMember provides a mock function with given fields: ctx, companyID, userID
func (_m *MembershipService) RemoveMember(ctx context.Context, companyID uuid.UUID, userID uuid.UUID) error {
	ret := _m.Called(ctx, companyID, userID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, companyID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MembershipService_RemoveMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveMember'
type MembershipService_RemoveMember_Call struct {
	*mock.Call
}

// RemoveMember is a helper method to define mock.On call
//   - ctx context.Context
//   - companyID uuid.UUID
//   - userID uuid.UUID
func (_e *MembershipService_Expecter) RemoveMember(ctx interface{}, companyID interface{}, userID interface{}) *MembershipService_RemoveMember_Call {
	return &MembershipService_RemoveMember_Call{Call: _e.mock.On("RemoveMember", ctx, companyID, userID)}
}

func (_c *MembershipService_RemoveMember_Call) Run(run func(ctx context.Context, companyID uuid.UUID, userID uuid.UUID)) *MembershipService_RemoveMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MembershipService_RemoveMember_Call) Return(_a0 error) *MembershipService_RemoveMember_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MembershipService_RemoveMember_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MembershipService_RemoveMember_Call {
	_c.Call.Return(run)
	return _c
}

// NewMembershipService creates a new instance of MembershipService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMembershipService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MembershipService {
	mock := &MembershipService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
