// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/clevertechware/gerer-les-transactions-en-base-de-donnees-golang/internal/domain"

	mock "github.com/stretchr/testify/mock"

	service "github.com/clevertechware/gerer-les-transactions-en-base-de-donnees-golang/internal/service"
)

// OnboardingService is an autogenerated mock type for the onboardingService type
type OnboardingService struct {
	mock.Mock
}

type OnboardingService_Expecter struct {
	mock *mock.Mock
}

func (_m *OnboardingService) EXPECT() *OnboardingService_Expecter {
	return &OnboardingService_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, input
func (_m *OnboardingService) Execute(ctx context.Context, input service.OnboardingInput) (*domain.Onboarding, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *domain.Onboarding
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, service.OnboardingInput) (*domain.Onboarding, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.OnboardingInput) *domain.Onboarding); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Onboarding)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.OnboardingInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OnboardingService_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type OnboardingService_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - input service.OnboardingInput
func (_e *OnboardingService_Expecter) Execute(ctx interface{}, input interface{}) *OnboardingService_Execute_Call {
	return &OnboardingService_Execute_Call{Call: _e.mock.On("Execute", ctx, input)}
}

func (_c *OnboardingService_Execute_Call) Run(run func(ctx context.Context, input service.OnboardingInput)) *OnboardingService_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(service.OnboardingInput))
	})
	return _c
}

func (_c *OnboardingService_Execute_Call) Return(_a0 *domain.Onboarding, _a1 error) *OnboardingService_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OnboardingService_Execute_Call) RunAndReturn(run func(context.Context, service.OnboardingInput) (*domain.Onboarding, error)) *OnboardingService_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewOnboardingService creates a new instance of OnboardingService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOnboardingService(t interface {
	mock.TestingT
	Cleanup(func())
}) *OnboardingService {
	mock := &OnboardingService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
