// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	service "github.com/clevertechware/gerer-les-transactions-en-base-de-donnees/internal/service"

	uuid "github.com/google/uuid"
)

// ReportService is an autogenerated mock type for the reportService type
type ReportService struct {
	mock.Mock
}

type ReportService_Expecter struct {
	mock *mock.Mock
}

func (_m *ReportService) EXPECT() *ReportService_Expecter {
	return &ReportService_Expecter{mock: &_m.Mock}
}

// CompanyReport provides a mock function with given fields: ctx, companyID
func (_m *ReportService) CompanyReport(ctx context.Context, companyID uuid.UUID) (*service.CompanyReport, error) {
	ret := _m.Called(ctx, companyID)

	if len(ret) == 0 {
		panic("no return value specified for CompanyReport")
	}

	var r0 *service.CompanyReport
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*service.CompanyReport, error)); ok {
		return rf(ctx, companyID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *service.CompanyReport); ok {
		r0 = rf(ctx, companyID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.CompanyReport)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, companyID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReportService_CompanyReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompanyReport'
type ReportService_CompanyReport_Call struct {
	*mock.Call
}

// CompanyReport is a helper method to define mock.On call
//   - ctx context.Context
//   - companyID uuid.UUID
func (_e *ReportService_Expecter) CompanyReport(ctx interface{}, companyID interface{}) *ReportService_CompanyReport_Call {
	return &ReportService_CompanyReport_Call{Call: _e.mock.On("CompanyReport", ctx, companyID)}
}

func (_c *ReportService_CompanyReport_Call) Run(run func(ctx context.Context, companyID uuid.UUID)) *ReportService_CompanyReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *ReportService_CompanyReport_Call) Return(_a0 *service.CompanyReport, _a1 error) *ReportService_CompanyReport_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReportService_CompanyReport_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*service.CompanyReport, error)) *ReportService_CompanyReport_Call {
	_c.Call.Return(run)
	return _c
}

// NewReportService creates a new instance of ReportService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReportService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReportService {
	mock := &ReportService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
