// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/clevertechware/handling-db-transactions-in-golang/internal/domain"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// VerificationService is an autogenerated mock type for the verificationService type
type VerificationService struct {
	mock.Mock
}

type VerificationService_Expecter struct {
	mock *mock.Mock
}

func (_m *VerificationService) EXPECT() *VerificationService_Expecter {
	return &VerificationService_Expecter{mock: &_m.Mock}
}

// VerifyBad provides a mock function with given fields: ctx, companyID
func (_m *VerificationService) VerifyBad(ctx context.Context, companyID uuid.UUID) (*domain.Company, error) {
	ret := _m.Called(ctx, companyID)

	if len(ret) == 0 {
		panic("no return value specified for VerifyBad")
	}

	var r0 *domain.Company
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Company, error)); ok {
		return rf(ctx, companyID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Company); ok {
		r0 = rf(ctx, companyID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Company)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, companyID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VerificationService_VerifyBad_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyBad'
type VerificationService_VerifyBad_Call struct {
	*mock.Call
}

// VerifyBad is a helper method to define mock.On call
//   - ctx context.Context
//   - companyID uuid.UUID
func (_e *VerificationService_Expecter) VerifyBad(ctx interface{}, companyID interface{}) *VerificationService_VerifyBad_Call {
	return &VerificationService_VerifyBad_Call{Call: _e.mock.On("VerifyBad", ctx, companyID)}
}

func (_c *VerificationService_VerifyBad_Call) Run(run func(ctx context.Context, companyID uuid.UUID)) *VerificationService_VerifyBad_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *VerificationService_VerifyBad_Call) Return(_a0 *domain.Company, _a1 error) *VerificationService_VerifyBad_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *VerificationService_VerifyBad_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.Company, error)) *VerificationService_VerifyBad_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyGood provides a mock function with given fields: ctx, companyID
func (_m *VerificationService) VerifyGood(ctx context.Context, companyID uuid.UUID) (*domain.Company, error) {
	ret := _m.Called(ctx, companyID)

	if len(ret) == 0 {
		panic("no return value specified for VerifyGood")
	}

	var r0 *domain.Company
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Company, error)); ok {
		return rf(ctx, companyID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Company); ok {
		r0 = rf(ctx, companyID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Company)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, companyID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VerificationService_VerifyGood_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyGood'
type VerificationService_VerifyGood_Call struct {
	*mock.Call
}

// VerifyGood is a helper method to define mock.On call
//   - ctx context.Context
//   - companyID uuid.UUID
func (_e *VerificationService_Expecter) VerifyGood(ctx interface{}, companyID interface{}) *VerificationService_VerifyGood_Call {
	return &VerificationService_VerifyGood_Call{Call: _e.mock.On("VerifyGood", ctx, companyID)}
}

func (_c *VerificationService_VerifyGood_Call) Run(run func(ctx context.Context, companyID uuid.UUID)) *VerificationService_VerifyGood_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *VerificationService_VerifyGood_Call) Return(_a0 *domain.Company, _a1 error) *VerificationService_VerifyGood_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *VerificationService_VerifyGood_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.Company, error)) *VerificationService_VerifyGood_Call {
	_c.Call.Return(run)
	return _c
}

// NewVerificationService creates a new instance of VerificationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVerificationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *VerificationService {
	mock := &VerificationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
