// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/clevertechware/handling-db-transactions-in-golang/internal/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// CompanyRepository is an autogenerated mock type for the companyRepository type
type CompanyRepository struct {
	mock.Mock
}

type CompanyRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *CompanyRepository) EXPECT() *CompanyRepository_Expecter {
	return &CompanyRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, company
func (_m *CompanyRepository) Create(ctx context.Context, company *domain.Company) error {
	ret := _m.Called(ctx, company)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Company) error); ok {
		r0 = rf(ctx, company)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CompanyRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type CompanyRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - company *domain.Company
func (_e *CompanyRepository_Expecter) Create(ctx interface{}, company interface{}) *CompanyRepository_Create_Call {
	return &CompanyRepository_Create_Call{Call: _e.mock.On("Create", ctx, company)}
}

func (_c *CompanyRepository_Create_Call) Run(run func(ctx context.Context, company *domain.Company)) *CompanyRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Company))
	})
	return _c
}

func (_c *CompanyRepository_Create_Call) Return(_a0 error) *CompanyRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CompanyRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.Company) error) *CompanyRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *CompanyRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CompanyRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type CompanyRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *CompanyRepository_Expecter) Delete(ctx interface{}, id interface{}) *CompanyRepository_Delete_Call {
	return &CompanyRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *CompanyRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *CompanyRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *CompanyRepository_Delete_Call) Return(_a0 error) *CompanyRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CompanyRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *CompanyRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *CompanyRepository) GetByID(ctx context.Context, id uuid.UUID) (*domain.Company, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Company
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Company, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Company); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Company)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CompanyRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type CompanyRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *CompanyRepository_Expecter) GetByID(ctx interface{}, id interface{}) *CompanyRepository_GetByID_Call {
	return &CompanyRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *CompanyRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *CompanyRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *CompanyRepository_GetByID_Call) Return(_a0 *domain.Company, _a1 error) *CompanyRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CompanyRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.Company, error)) *CompanyRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx
func (_m *CompanyRepository) List(ctx context.Context) ([]domain.Company, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.Company
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Company, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Company); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Company)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CompanyRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type CompanyRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *CompanyRepository_Expecter) List(ctx interface{}) *CompanyRepository_List_Call {
	return &CompanyRepository_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *CompanyRepository_List_Call) Run(run func(ctx context.Context)) *CompanyRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *CompanyRepository_List_Call) Return(_a0 []domain.Company, _a1 error) *CompanyRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CompanyRepository_List_Call) RunAndReturn(run func(context.Context) ([]domain.Company, error)) *CompanyRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// LockForUpdate provides a mock function with given fields: ctx, id
func (_m *CompanyRepository) LockForUpdate(ctx context.Context, id uuid.UUID) (*domain.Company, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for LockForUpdate")
	}

	var r0 *domain.Company
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Company, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Company); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Company)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CompanyRepository_LockForUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LockForUpdate'
type CompanyRepository_LockForUpdate_Call struct {
	*mock.Call
}

// LockForUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *CompanyRepository_Expecter) LockForUpdate(ctx interface{}, id interface{}) *CompanyRepository_LockForUpdate_Call {
	return &CompanyRepository_LockForUpdate_Call{Call: _e.mock.On("LockForUpdate", ctx, id)}
}

func (_c *CompanyRepository_LockForUpdate_Call) Run(run func(ctx context.Context, id uuid.UUID)) *CompanyRepository_LockForUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *CompanyRepository_LockForUpdate_Call) Return(_a0 *domain.Company, _a1 error) *CompanyRepository_LockForUpdate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CompanyRepository_LockForUpdate_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.Company, error)) *CompanyRepository_LockForUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// MarkVerified provides a mock function with given fields: ctx, id, reference
func (_m *CompanyRepository) MarkVerified(ctx context.Context, id uuid.UUID, reference string) (*domain.Company, error) {
	ret := _m.Called(ctx, id, reference)

	if len(ret) == 0 {
		panic("no return value specified for MarkVerified")
	}

	var r0 *domain.Company
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (*domain.Company, error)); ok {
		return rf(ctx, id, reference)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) *domain.Company); ok {
		r0 = rf(ctx, id, reference)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Company)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, id, reference)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CompanyRepository_MarkVerified_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkVerified'
type CompanyRepository_MarkVerified_Call struct {
	*mock.Call
}

// MarkVerified is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - reference string
func (_e *CompanyRepository_Expecter) MarkVerified(ctx interface{}, id interface{}, reference interface{}) *CompanyRepository_MarkVerified_Call {
	return &CompanyRepository_MarkVerified_Call{Call: _e.mock.On("MarkVerified", ctx, id, reference)}
}

func (_c *CompanyRepository_MarkVerified_Call) Run(run func(ctx context.Context, id uuid.UUID, reference string)) *CompanyRepository_MarkVerified_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *CompanyRepository_MarkVerified_Call) Return(_a0 *domain.Company, _a1 error) *CompanyRepository_MarkVerified_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CompanyRepository_MarkVerified_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) (*domain.Company, error)) *CompanyRepository_MarkVerified_Call {
	_c.Call.Return(run)
	return _c
}

// SetVerified provides a mock function with given fields: ctx, id, reference
func (_m *CompanyRepository) SetVerified(ctx context.Context, id uuid.UUID, reference string) error {
	ret := _m.Called(ctx, id, reference)

	if len(ret) == 0 {
		panic("no return value specified for SetVerified")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = rf(ctx, id, reference)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CompanyRepository_SetVerified_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetVerified'
type CompanyRepository_SetVerified_Call struct {
	*mock.Call
}

// SetVerified is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - reference string
func (_e *CompanyRepository_Expecter) SetVerified(ctx interface{}, id interface{}, reference interface{}) *CompanyRepository_SetVerified_Call {
	return &CompanyRepository_SetVerified_Call{Call: _e.mock.On("SetVerified", ctx, id, reference)}
}

func (_c *CompanyRepository_SetVerified_Call) Run(run func(ctx context.Context, id uuid.UUID, reference string)) *CompanyRepository_SetVerified_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *CompanyRepository_SetVerified_Call) Return(_a0 error) *CompanyRepository_SetVerified_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CompanyRepository_SetVerified_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) error) *CompanyRepository_SetVerified_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, company
func (_m *CompanyRepository) Update(ctx context.Context, company *domain.Company) error {
	ret := _m.Called(ctx, company)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Company) error); ok {
		r0 = rf(ctx, company)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CompanyRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type CompanyRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - company *domain.Company
func (_e *CompanyRepository_Expecter) Update(ctx interface{}, company interface{}) *CompanyRepository_Update_Call {
	return &CompanyRepository_Update_Call{Call: _e.mock.On("Update", ctx, company)}
}

func (_c *CompanyRepository_Update_Call) Run(run func(ctx context.Context, company *domain.Company)) *CompanyRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Company))
	})
	return _c
}

func (_c *CompanyRepository_Update_Call) Return(_a0 error) *CompanyRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CompanyRepository_Update_Call) RunAndReturn(run func(context.Context, *domain.Company) error) *CompanyRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewCompanyRepository creates a new instance of CompanyRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCompanyRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CompanyRepository {
	mock := &CompanyRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
