// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/clevertechware/handling-db-transactions-in-golang/internal/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MembershipRepository is an autogenerated mock type for the membershipRepository type
type MembershipRepository struct {
	mock.Mock
}

type MembershipRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MembershipRepository) EXPECT() *MembershipRepository_Expecter {
	return &MembershipRepository_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: ctx, membership
func (_m *MembershipRepository) Add(ctx context.Context, membership *domain.Membership) error {
	ret := _m.Called(ctx, membership)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Membership) error); ok {
		r0 = rf(ctx, membership)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MembershipRepository_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MembershipRepository_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - membership *domain.Membership
func (_e *MembershipRepository_Expecter) Add(ctx interface{}, membership interface{}) *MembershipRepository_Add_Call {
	return &MembershipRepository_Add_Call{Call: _e.mock.On("Add", ctx, membership)}
}

func (_c *MembershipRepository_Add_Call) Run(run func(ctx context.Context, membership *domain.Membership)) *MembershipRepository_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Membership))
	})
	return _c
}

func (_c *MembershipRepository_Add_Call) Return(_a0 error) *MembershipRepository_Add_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MembershipRepository_Add_Call) RunAndReturn(run func(context.Context, *domain.Membership) error) *MembershipRepository_Add_Call {
	_c.Call.Return(run)
	return _c
}

// CountByCompany provides a mock function with given fields: ctx, companyID
func (_m *MembershipRepository) CountByCompany(ctx context.Context, companyID uuid.UUID) (int, error) {
	ret := _m.Called(ctx, companyID)

	if len(ret) == 0 {
		panic("no return value specified for CountByCompany")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int, error)); ok {
		return rf(ctx, companyID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) int); ok {
		r0 = rf(ctx, companyID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, companyID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MembershipRepository_CountByCompany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByCompany'
type MembershipRepository_CountByCompany_Call struct {
	*mock.Call
}

// CountByCompany is a helper method to define mock.On call
//   - ctx context.Context
//   - companyID uuid.UUID
func (_e *MembershipRepository_Expecter) CountByCompany(ctx interface{}, companyID interface{}) *MembershipRepository_CountByCompany_Call {
	return &MembershipRepository_CountByCompany_Call{Call: _e.mock.On("CountByCompany", ctx, companyID)}
}

func (_c *MembershipRepository_CountByCompany_Call) Run(run func(ctx context.Context, companyID uuid.UUID)) *MembershipRepository_CountByCompany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MembershipRepository_CountByCompany_Call) Return(_a0 int, _a1 error) *MembershipRepository_CountByCompany_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MembershipRepository_CountByCompany_Call) RunAndReturn(run func(context.Context, uuid.UUID) (int, error)) *MembershipRepository_CountByCompany_Call {
	_c.Call.Return(run)
	return _c
}

// ListByCompany provides a mock function with given fields: ctx, companyID
func (_m *MembershipRepository) ListByCompany(ctx context.Context, companyID uuid.UUID) ([]domain.Membership, error) {
	ret := _m.Called(ctx, companyID)

	if len(ret) == 0 {
		panic("no return value specified for ListByCompany")
	}

	var r0 []domain.Membership
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]domain.Membership, error)); ok {
		return rf(ctx, companyID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []domain.Membership); ok {
		r0 = rf(ctx, companyID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Membership)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, companyID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MembershipRepository_ListByCompany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByCompany'
type MembershipRepository_ListByCompany_Call struct {
	*mock.Call
}

// ListByCompany is a helper method to define mock.On call
//   - ctx context.Context
//   - companyID uuid.UUID
func (_e *MembershipRepository_Expecter) ListByCompany(ctx interface{}, companyID interface{}) *MembershipRepository_ListByCompany_Call {
	return &MembershipRepository_ListByCompany_Call{Call: _e.mock.On("ListByCompany", ctx, companyID)}
}

func (_c *MembershipRepository_ListByCompany_Call) Run(run func(ctx context.Context, companyID uuid.UUID)) *MembershipRepository_ListByCompany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MembershipRepository_ListByCompany_Call) Return(_a0 []domain.Membership, _a1 error) *MembershipRepository_ListByCompany_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MembershipRepository_ListByCompany_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]domain.Membership, error)) *MembershipRepository_ListByCompany_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function with given fields: ctx, companyID, userID
func (_m *MembershipRepository) Remove(ctx context.Context, companyID uuid.UUID, userID uuid.UUID) error {
	ret := _m.Called(ctx, companyID, userID)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, companyID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MembershipRepository_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type MembershipRepository_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - ctx context.Context
//   - companyID uuid.UUID
//   - userID uuid.UUID
func (_e *MembershipRepository_Expecter) Remove(ctx interface{}, companyID interface{}, userID interface{}) *MembershipRepository_Remove_Call {
	return &MembershipRepository_Remove_Call{Call: _e.mock.On("Remove", ctx, companyID, userID)}
}

func (_c *MembershipRepository_Remove_Call) Run(run func(ctx context.Context, companyID uuid.UUID, userID uuid.UUID)) *MembershipRepository_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MembershipRepository_Remove_Call) Return(_a0 error) *MembershipRepository_Remove_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MembershipRepository_Remove_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MembershipRepository_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// NewMembershipRepository creates a new instance of MembershipRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMembershipRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MembershipRepository {
	mock := &MembershipRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
