// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// VerificationGateway is an autogenerated mock type for the verificationGateway type
type VerificationGateway struct {
	mock.Mock
}

type VerificationGateway_Expecter struct {
	mock *mock.Mock
}

func (_m *VerificationGateway) EXPECT() *VerificationGateway_Expecter {
	return &VerificationGateway_Expecter{mock: &_m.Mock}
}

// Verify provides a mock function with given fields: ctx, companyName
func (_m *VerificationGateway) Verify(ctx context.Context, companyName string) (string, error) {
	ret := _m.Called(ctx, companyName)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, companyName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, companyName)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, companyName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VerificationGateway_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type VerificationGateway_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - ctx context.Context
//   - companyName string
func (_e *VerificationGateway_Expecter) Verify(ctx interface{}, companyName interface{}) *VerificationGateway_Verify_Call {
	return &VerificationGateway_Verify_Call{Call: _e.mock.On("Verify", ctx, companyName)}
}

func (_c *VerificationGateway_Verify_Call) Run(run func(ctx context.Context, companyName string)) *VerificationGateway_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *VerificationGateway_Verify_Call) Return(reference string, err error) *VerificationGateway_Verify_Call {
	_c.Call.Return(reference, err)
	return _c
}

func (_c *VerificationGateway_Verify_Call) RunAndReturn(run func(context.Context, string) (string, error)) *VerificationGateway_Verify_Call {
	_c.Call.Return(run)
	return _c
}

// NewVerificationGateway creates a new instance of VerificationGateway. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVerificationGateway(t interface {
	mock.TestingT
	Cleanup(func())
}) *VerificationGateway {
	mock := &VerificationGateway{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
