// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Scanner is an autogenerated mock type for the scanner type
type Scanner struct {
	mock.Mock
}

type Scanner_Expecter struct {
	mock *mock.Mock
}

func (_m *Scanner) EXPECT() *Scanner_Expecter {
	return &Scanner_Expecter{mock: &_m.Mock}
}

// Scan provides a mock function with given fields: dest
func (_m *Scanner) Scan(dest ...any) error {
	var _ca []interface{}
	_ca = append(_ca, dest...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Scan")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(...any) error); ok {
		r0 = rf(dest...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Scanner_Scan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Scan'
type Scanner_Scan_Call struct {
	*mock.Call
}

// Scan is a helper method to define mock.On call
//   - dest ...any
func (_e *Scanner_Expecter) Scan(dest ...interface{}) *Scanner_Scan_Call {
	return &Scanner_Scan_Call{Call: _e.mock.On("Scan",
		append([]interface{}{}, dest...)...)}
}

func (_c *Scanner_Scan_Call) Run(run func(dest ...any)) *Scanner_Scan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]any, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *Scanner_Scan_Call) Return(_a0 error) *Scanner_Scan_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Scanner_Scan_Call) RunAndReturn(run func(...any) error) *Scanner_Scan_Call {
	_c.Call.Return(run)
	return _c
}

// NewScanner creates a new instance of Scanner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewScanner(t interface {
	mock.TestingT
	Cleanup(func())
}) *Scanner {
	mock := &Scanner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
