// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	transaction "github.com/clevertechware/gerer-les-transactions-en-base-de-donnees-golang/pkg/transaction"
	mock "github.com/stretchr/testify/mock"
)

// Manager is an autogenerated mock type for the Manager type
type Manager struct {
	mock.Mock
}

type Manager_Expecter struct {
	mock *mock.Mock
}

func (_m *Manager) EXPECT() *Manager_Expecter {
	return &Manager_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, unitOfWork
func (_m *Manager) Execute(ctx context.Context, unitOfWork transaction.UnitOfWork) error {
	ret := _m.Called(ctx, unitOfWork)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, transaction.UnitOfWork) error); ok {
		r0 = rf(ctx, unitOfWork)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Manager_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type Manager_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - unitOfWork transaction.UnitOfWork
func (_e *Manager_Expecter) Execute(ctx interface{}, unitOfWork interface{}) *Manager_Execute_Call {
	return &Manager_Execute_Call{Call: _e.mock.On("Execute", ctx, unitOfWork)}
}

func (_c *Manager_Execute_Call) Run(run func(ctx context.Context, unitOfWork transaction.UnitOfWork)) *Manager_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(transaction.UnitOfWork))
	})
	return _c
}

func (_c *Manager_Execute_Call) Return(_a0 error) *Manager_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Manager_Execute_Call) RunAndReturn(run func(context.Context, transaction.UnitOfWork) error) *Manager_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// ExecuteReadOnly provides a mock function with given fields: ctx, unitOfWork
func (_m *Manager) ExecuteReadOnly(ctx context.Context, unitOfWork transaction.UnitOfWork) error {
	ret := _m.Called(ctx, unitOfWork)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteReadOnly")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, transaction.UnitOfWork) error); ok {
		r0 = rf(ctx, unitOfWork)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Manager_ExecuteReadOnly_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecuteReadOnly'
type Manager_ExecuteReadOnly_Call struct {
	*mock.Call
}

// ExecuteReadOnly is a helper method to define mock.On call
//   - ctx context.Context
//   - unitOfWork transaction.UnitOfWork
func (_e *Manager_Expecter) ExecuteReadOnly(ctx interface{}, unitOfWork interface{}) *Manager_ExecuteReadOnly_Call {
	return &Manager_ExecuteReadOnly_Call{Call: _e.mock.On("ExecuteReadOnly", ctx, unitOfWork)}
}

func (_c *Manager_ExecuteReadOnly_Call) Run(run func(ctx context.Context, unitOfWork transaction.UnitOfWork)) *Manager_ExecuteReadOnly_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(transaction.UnitOfWork))
	})
	return _c
}

func (_c *Manager_ExecuteReadOnly_Call) Return(_a0 error) *Manager_ExecuteReadOnly_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Manager_ExecuteReadOnly_Call) RunAndReturn(run func(context.Context, transaction.UnitOfWork) error) *Manager_ExecuteReadOnly_Call {
	_c.Call.Return(run)
	return _c
}

// ExecuteSerializable provides a mock function with given fields: ctx, unitOfWork
func (_m *Manager) ExecuteSerializable(ctx context.Context, unitOfWork transaction.UnitOfWork) error {
	ret := _m.Called(ctx, unitOfWork)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteSerializable")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, transaction.UnitOfWork) error); ok {
		r0 = rf(ctx, unitOfWork)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Manager_ExecuteSerializable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecuteSerializable'
type Manager_ExecuteSerializable_Call struct {
	*mock.Call
}

// ExecuteSerializable is a helper method to define mock.On call
//   - ctx context.Context
//   - unitOfWork transaction.UnitOfWork
func (_e *Manager_Expecter) ExecuteSerializable(ctx interface{}, unitOfWork interface{}) *Manager_ExecuteSerializable_Call {
	return &Manager_ExecuteSerializable_Call{Call: _e.mock.On("ExecuteSerializable", ctx, unitOfWork)}
}

func (_c *Manager_ExecuteSerializable_Call) Run(run func(ctx context.Context, unitOfWork transaction.UnitOfWork)) *Manager_ExecuteSerializable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(transaction.UnitOfWork))
	})
	return _c
}

func (_c *Manager_ExecuteSerializable_Call) Return(_a0 error) *Manager_ExecuteSerializable_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Manager_ExecuteSerializable_Call) RunAndReturn(run func(context.Context, transaction.UnitOfWork) error) *Manager_ExecuteSerializable_Call {
	_c.Call.Return(run)
	return _c
}

// NewManager creates a new instance of Manager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *Manager {
	mock := &Manager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
